/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this script OnEnter
void main()
{

object oPC = GetEnteringObject();

if (!GetIsPC(oPC)) return;

AddJournalQuestEntry("Rules", 1, oPC, FALSE, FALSE, TRUE);

AddJournalQuestEntry("Who do I contact?", 1, oPC, FALSE, FALSE, TRUE);

AddJournalQuestEntry("Chat Commands", 1, oPC, FALSE, FALSE, TRUE);

}

